### ISSUE TITLE
Unit test `rSOILWAT2 annual aggregation` for slot `SWA` fail

### ISSUE THREAD

**Issue by dschlaep** [DrylandEcology/rSOILWAT2#116]
With commit 56137d5263ece4384e65fcba986e4937fcc93443

```
Testing rSOILWAT2
✔ | OK F W S | Context
✔ | 21       | Carbon dioxide class [0.1 s]
✔ | 72       | Vegetation parameters class [0.7 s]
✔ | 17       | Site parameters class [0.1 s]
✔ | 34       | rSOILWAT2 data access functions [0.3 s]
✔ | 139       | rSOILWAT2 weather database [1.6 s]
✖ | 282 3     | rSOILWAT2 annual aggregation [6.9 s]
────────────────────────────────────────────────────────────────────────────────
test_exec_and_aggregate.R:65: failure: Simulate and aggregate
sum(abs(x1@Day[, -(1:2)])) > 0 isn't true.
test-data Ex1 - slot SWA

test_exec_and_aggregate.R:66: failure: Simulate and aggregate
sum(abs(x1@Year[, -1])) > 0 isn't true.
test-data Ex1 - slot SWA

test_exec_and_aggregate.R:74: failure: Simulate and aggregate
{
    ...
} not equivalent to `res_true`.
'is.NA' value mismatch: 0 in current 62 in target
test-data Ex1 - slot SWA
────────────────────────────────────────────────────────────────────────────────
✔ |  1       | rSOILWAT2 segfault [0.2 s]
✔ | 53       | rSOILWAT2 soil temperature instability [2.4 s]
✔ | 245       | rSOILWAT2 water balance [4.1 s]

══ Results ═════════════════════════════════════════════════════════════════════
Duration: 16.6 s

OK:       864
Failed:   3
Warnings: 0
Skipped:  0
```

**Comment by BrendenBe1** [comment]
This should be resolved with the latest commit. I just made a clean clone and checked out my branch and ran the tests and run_examples and everything worked.

**Comment by dschlaep** [comment]
This has not been resolved. This is still failing as of commit f66444e

**Comment by dschlaep** [comment]
These unit tests pass when I run them via Rstudio, but they fail when I run them in R via terminal and in the R.app. Crazy weird.

**Comment by dschlaep** [comment]
Ok, the reason why this issue arising or not is because `swa_total_Lyr_*` may be filled with crazy large or small values (then the unit tests pass) or alternatively and correctly with 0 (then the unit tests fail).

-- I guess that this is an initialization problem?

```
> head(x1@Year[, -1])
     swa_total_Lyr_1 swa_total_Lyr_2 swa_total_Lyr_3 swa_total_Lyr_4 swa_total_Lyr_5 swa_total_Lyr_6
[1,]    4.591635e-41    2.802597e-45        3899.321     4.61854e-41   -1.140819e+20    4.591915e-41
[2,]    4.591635e-41    2.802597e-45        3899.321     4.61854e-41   -1.140819e+20    4.591915e-41
[3,]    4.591635e-41    2.802597e-45        3899.321     4.61854e-41   -1.140819e+20    4.591915e-41
[4,]    4.591635e-41    2.802597e-45        3899.321     4.61854e-41   -1.140819e+20    4.591915e-41
[5,]    4.591635e-41    2.802597e-45        3899.321     4.61854e-41   -1.140819e+20    4.591915e-41
[6,]    4.591635e-41    2.802597e-45        3899.321     4.61854e-41   -1.140819e+20    4.591915e-41
     swa_total_Lyr_7 swa_total_Lyr_8 swa_tree_Lyr_1 swa_tree_Lyr_2 swa_tree_Lyr_3 swa_tree_Lyr_4
[1,]    2.722562e+15    3.198912e-39              0              0              0              0
[2,]    2.722562e+15    3.198912e-39              0              0              0              0
[3,]    2.722562e+15    3.198912e-39              0              0              0              0
[4,]    2.722562e+15    3.198912e-39              0              0              0              0
[5,]    2.722562e+15    3.198912e-39              0              0              0              0
[6,]    2.722562e+15    3.198912e-39              0              0              0              0
```

**Comment by dschlaep** [comment]
With the new unit tests (commit b2561cfed32809c49b7353fae924f9225bf04cf7), the unit tests consistently fail for SWA 

```
test_exec_and_aggregate.R:137: failure: Simulate and aggregate
sum(abs(x2[, -ch[[its]]])) > 0 isn't true.
test-data Ex1 - slot SWA - timestep Day

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
'is.NA' value mismatch: 0 in current 1 in target
test-data Ex1 - slot SWA - timestep Day - soillayer 1

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
'is.NA' value mismatch: 0 in current 1 in target
test-data Ex1 - slot SWA - timestep Day - soillayer 2

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex1 - slot SWA - timestep Day - soillayer 3

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex1 - slot SWA - timestep Day - soillayer 5

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex1 - slot SWA - timestep Day - soillayer 6

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex1 - slot SWA - timestep Day - soillayer 7

test_exec_and_aggregate.R:137: failure: Simulate and aggregate
sum(abs(x2[, -ch[[its]]])) > 0 isn't true.
test-data Ex1 - slot SWA - timestep Year

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
'is.NA' value mismatch: 0 in current 1 in target
test-data Ex1 - slot SWA - timestep Year - soillayer 1

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
'is.NA' value mismatch: 0 in current 1 in target
test-data Ex1 - slot SWA - timestep Year - soillayer 2

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex1 - slot SWA - timestep Year - soillayer 3

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex1 - slot SWA - timestep Year - soillayer 5

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex1 - slot SWA - timestep Year - soillayer 6

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex1 - slot SWA - timestep Year - soillayer 7

test_exec_and_aggregate.R:171: failure: Simulate and aggregate
{
    ...
} not equivalent to `res_true`.
'is.NA' value mismatch: 0 in current 62 in target
test-data Ex1 - slot SWA

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex2 - slot SWA - timestep Day - soillayer 6

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex2 - slot SWA - timestep Day - soillayer 7

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex2 - slot SWA - timestep Year - soillayer 6

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex2 - slot SWA - timestep Year - soillayer 7

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex3 - slot SWA - timestep Day - soillayer 6

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex3 - slot SWA - timestep Day - soillayer 7

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex3 - slot SWA - timestep Year - soillayer 6

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex3 - slot SWA - timestep Year - soillayer 7

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex4 - slot SWA - timestep Day - soillayer 6

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex4 - slot SWA - timestep Day - soillayer 7

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex4 - slot SWA - timestep Year - soillayer 6

test_exec_and_aggregate.R:154: failure: Simulate and aggregate
`within` not equivalent to TRUE.
1 element mismatch
test-data Ex4 - slot SWA - timestep Year - soillayer 7
```

**Comment by BrendenBe1** [comment]
For swa there is no swa_total column which would explain why the tests are failing and giving strange numbers.

**Comment by dschlaep** [comment]
Yes, I agree. It doesn't make sense to have `swa_total_*` output columns because our SWA values are not additive in a meaningful sense.

**Comment by BrendenBe1** [comment]
I made it so there is no 'total' column for swa with rSOILWAT by changing the SW_OUT_set_colnames function. When printing out all the values in SW_Output.c as the tests are running all of the values are 0 but the tests are giving swa_tree values that are not 0. I don't know why this is happening since all the values are set as 0 in the actual code. 

```
swa_tree_Lyr_1 swa_tree_Lyr_2 swa_tree_Lyr_3 swa_tree_Lyr_4 swa_tree_Lyr_5 swa_tree_Lyr_6 swa_tree_Lyr_7 swa_tree_Lyr_8 swa_shrub_Lyr_1 swa_shrub_Lyr_2
[1,]   1.440031e-37              0            NaN   3.698925e-34   2.844636e-43  -3.420036e+34   1.440477e-37  -3.419503e+34               0               0
[2,]   1.440031e-37              0            NaN   3.698925e-34   2.844636e-43  -3.420036e+34   1.440477e-37  -3.419503e+34               0               0
[3,]   1.440031e-37              0            NaN   3.698925e-34   2.844636e-43  -3.420036e+34   1.440477e-37  -3.419503e+34               0               0
[4,]   1.440031e-37              0            NaN   3.698925e-34   2.844636e-43  -3.420036e+34   1.440477e-37  -3.419503e+34               0               0
[5,]   1.440031e-37              0            NaN   3.698925e-34   2.844636e-43  -3.420036e+34   1.440477e-37  -3.419503e+34               0               0
[6,]   1.440031e-37              0            NaN   3.698925e-34   2.844636e-43  -3.420036e+34   1.440477e-37  -3.419503e+34               0               0
     swa_shrub_Lyr_3 swa_shrub_Lyr_4 swa_shrub_Lyr_5 swa_shrub_Lyr_6 swa_shrub_Lyr_7 swa_shrub_Lyr_8 swa_forbs_Lyr_1 swa_forbs_Lyr_2 swa_forbs_Lyr_3 swa_forbs_Lyr_4
[1,]               0               0               0               0               0               0               0               0               0               0
[2,]               0               0               0               0               0               0               0               0               0               0
[3,]               0               0               0               0               0               0               0               0               0               0
[4,]               0               0               0               0               0               0               0               0               0               0
[5,]               0               0               0               0               0               0               0               0               0               0
[6,]               0               0               0               0               0               0               0               0               0               0
     swa_forbs_Lyr_5 swa_forbs_Lyr_6 swa_forbs_Lyr_7 swa_forbs_Lyr_8 swa_grass_Lyr_1 swa_grass_Lyr_2 swa_grass_Lyr_3 swa_grass_Lyr_4 swa_grass_Lyr_5 swa_grass_Lyr_6
[1,]               0               0               0               0               0               0               0               0               0               0
[2,]               0               0               0               0               0               0               0               0               0               0
[3,]               0               0               0               0               0               0               0               0               0               0
[4,]               0               0               0               0               0               0               0               0               0               0
[5,]               0               0               0               0               0               0               0               0               0               0
[6,]               0               0               0               0               0               0               0               0               0               0
     swa_grass_Lyr_7 swa_grass_Lyr_8
[1,]               0               0
[2,]               0               0
[3,]               0               0
[4,]               0               0
[5,]               0               0
[6,]               0               0
```

**Comment by BrendenBe1** [comment]
What exactly is this test looking for? All of the values for swa are 0 but the tests are still failing.

**Comment by BrendenBe1** [comment]
@dschlaep all these unit tests are passing now.

**Comment by dschlaep** [comment]
Yes, for me too with commit 1ab301f2a9508237205db95e73585cbf193a0ac8. Good job!
